version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
      - npm install -g aws-cli

  pre_build:
    commands:
      - echo "Starting build..."
      - npm --version
      - node --version
      - echo "Verifying Next.js installation"

  build:
    commands:
      - echo "Building Next.js application"
      - npm run build
      - echo "Exporting static files"
      - npm run export
      - echo "Verifying build output"
      - ls -la out

  post_build:
    commands:
      - echo "Build complete at `date`"
      - echo "Verifying artifacts"
      - ls -la out
      - aws s3 rm s3://celeste7.ai --recursive
      - aws s3 sync out/ s3://celeste7.ai --delete
      - aws s3 cp out/index.html s3://celeste7.ai/index.html
      - aws s3 website s3://celeste7.ai --index-document index.html --error-document 404.html
      - echo "Invalidating CloudFront cache"
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: 'out'

cache:
  paths:
    - 'node_modules/**/*' 