version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install -g aws-cli

  pre_build:
    commands:
      - echo "Starting build process..."
      - npm --version
      - node --version

  build:
    commands:
      - echo "Building Next.js application..."
      - npm run build
      - echo "Exporting static files..."
      - npm run export
      - echo "Verifying build output..."
      - ls -la out/
      - echo "Checking for index.html..."
      - test -f out/index.html || (echo "index.html not found in out/ directory" && exit 1)

  post_build:
    commands:
      - echo "Build completed at `date`"
      - echo "Cleaning S3 bucket..."
      - aws s3 rm s3://celeste7.ai --recursive
      - echo "Uploading static files to S3..."
      - aws s3 sync out/ s3://celeste7.ai --delete
      - echo "Ensuring index.html is at root..."
      - aws s3 cp out/index.html s3://celeste7.ai/index.html
      - echo "Configuring website hosting..."
      - aws s3 website s3://celeste7.ai --index-document index.html --error-document 404.html
      - echo "Deployment completed successfully"

artifacts:
  files:
    - '**/*'
  base-directory: 'out'

cache:
  paths:
    - 'node_modules/**/*' 