version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci
      - npm install @plasmicapp/loader-nextjs@latest
      - npm cache clean --force

  pre_build:
    commands:
      - echo "Starting build process"
      - npm --version
      - node --version
      - echo "Creating next.config.js"
      - |
        echo 'const { withPlasmic } = require("@plasmicapp/loader-nextjs");
        module.exports = withPlasmic({
          plasmic: {
            projects: [
              {
                projectId: "your-project-id",
                token: process.env.PLASMIC_TOKEN
              }
            ]
          }
        });' > next.config.js

  build:
    commands:
      - echo "Building Next.js application"
      - npm run build --no-lint
      - npm run export

  post_build:
    commands:
      - echo "Build completed on `date`"
      - ls -la .next
      - ls -la out
      - echo "Verifying build artifacts"

artifacts:
  files:
    - '**/*'
    - '!.git/**/*'
    - '!node_modules/**/*'
    - '!temp_repo/**/*'
    - '!.next/**/*'
  base-directory: out
  name: c7-ai-v1.5.1-build-$(date +%Y-%m-%d-%H-%M-%S)

cache:
  paths:
    - 'node_modules/**/*' 