version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci
      - npm cache clean --force

  pre_build:
    commands:
      - echo "Starting build..."
      - npm --version
      - node --version
      - echo "Verifying Next.js installation"

  build:
    commands:
      - echo "Building Next.js application"
      - npm run build
      - echo "Exporting static files"
      - npm run export
      - echo "Verifying build output"
      - ls -la out
      - echo "Checking for static export files"
      - find out -type f -name "*.html" | wc -l

  post_build:
    commands:
      - echo "Build complete at `date`"
      - echo "Verifying artifacts"
      - ls -la out
      - echo "Checking export directory structure"
      - find out -type d | sort

artifacts:
  base-directory: out
  files:
    - '**/*'
    - '!.git/**/*'
    - '!node_modules/**/*'
    - '!.next/**/*'

cache:
  paths:
    - 'node_modules/**/*' 